app/models.py
from datetime import datetime
from . import db

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True) 
    name = db.Column(db.String(64), unique=True)
    created_at = db.Column(db.Date, default=datetime.now())

    def __repr__(self):
        return f'<User: {self.name}>'
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class NameForm(FlaskForm):
    name = StringField('Enter a name?', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask 
from flask_bootstrap import Bootstrap 
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy 
from dotenv import load_dotenv

from config import config

# register third-party apps
bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()
load_dotenv()

def create_app(config_name):
    app = Flask(__name__, template_folder='templates') 
    
    app.config.from_object(config[config_name]) 
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)

    # Register context processor
    @app.context_processor
    def inject_app_title():
        return dict(app_name=app.config['APP_NAME'])

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from datetime import datetime
from flask import flash, render_template, request, session, redirect, url_for
 
from . import main
from app import db
from .forms import NameForm
from ..models import User

@main.route('/', methods=['GET', 'POST']) 
def index():
    form = NameForm()
    
    if form.validate_on_submit():
        name = form.name.data

        user = User.query.filter_by(name=name).first()
        if user:
            flash('User already exists!', 'error')
        else:
            new_user = User(name=name)
            db.session.add(new_user)
            db.session.commit()

            session['name'] = form.name.data
            flash('New user created!', 'success')
            return redirect(url_for('main.index')) 
    
    users = User.query.order_by(User.created_at.desc()).all()
    context_data = {
        'form': form,
        'name': session.get('name'),
        'current_time': datetime.now(),
        'users': users
    }
    return render_template('index.html', **context_data)


@main.route('/delete_user', methods=['POST'])
def delete_user():
    user_id = request.form['user_id']
    user = User.query.get(user_id)

    if not user:
        flash('User not found!', 'error')
    else:
        db.session.delete(user)
        db.session.commit()
        session.pop('name')
        flash('User deleted successfully!', 'success')
        
    return redirect(url_for('main.index'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flask Starter{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation"> 
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
                <span class="sr-only">Toggle navigation</span> 
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href="/">Flask Starter</a> 
        </div>
        <div class="navbar-collapse collapse"> 
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li> 
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for category, message in get_flashed_messages(with_categories=true) %}
        {% set category_class = 'danger' if category == 'error' else category %}
        <div class="alert alert-{{ category_class }}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}{{ app_name }}{% endblock %}

{% block page_content %}
{% import "bootstrap/wtf.html" as wtf %}
<div class="row">
    <div class="col-md-8">
        <div class="page-header">
            <h1>Hello, {% if name %}{{ name }}{% else %}Stranger{% endif %}!</h1>
            <p>The local date and time is <b>{{ moment(current_time).format('LLL') }}!</b></p> 
        </div>
        {{ wtf.quick_form(form) }}
    </div>
    <div class="col-md-4">
        <h2>All Users</h2>
        <ul>
            {% for user in users %}
                <li class="user-item">
                    <span>{{ user.name }}</span>
                    <form action="{{ url_for('main.delete_user') }}" method="POST">
                        <input type="hidden" name="user_id" value="{{ user.id }}">
                        <button type="submit" class="delete-btn">X</button>
                    </form>
                </li>
            {% else %}
                <li class="user-item">
                    <span>No users available.</span>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}